### ISSUE TITLE
Set characterset Unicode seems not work

### ISSUE THREAD

**Issue by mathieumante** [Codesleuth/esendex-node#19]
Hi,

when i pass the param characterset for Unicode message, it d'ont take care of it :(
Can you check please?

**Comment by Codesleuth** [comment]
Can you post an example and the output?

**Comment by Codesleuth** [comment]
It seems that the package I'm using, [xml2js](https://github.com/Leonidas-from-XIV/node-xml2js), doesn't specify `allowSurrogateChars` (nor allow it to be set) in the builder.

I've set up a pull request for this issue. If this does not get resolved soon, I will publish my forked version of the package into the SDK.

See: https://github.com/Leonidas-from-XIV/node-xml2js/pull/266

**Comment by mathieumante** [comment]
Ok thanks @Codesleuth 
I wait for ^^

**Comment by Codesleuth** [comment]
When support is added in the `xml2js` dependency, I'll modify this package to use that. For now, please install the latest patch release due to be pushed soon.

**Comment by Codesleuth** [comment]
@mathieumante I've just included the latest `xml2js` package as a dependency, which contains a fix for this issue, rather than using my fork. I'll schedule an NPM release of the package through Esendex, which may be Monday.
